/**
 * tikz-timing export backend — generate LaTeX `tikz-timing` source from the
 * model so users can drop a diagram straight into a paper. Pure (no DOM).
 *
 * Output uses a `tikztimingtable`. Each cycle is one time-unit; clocks render as
 * two half-units (`0.5H0.5L`). Requires `\usepackage{tikz-timing}` in the doc.
 */
import type { Brick } from './bricks';
import type { NormModel } from './model';
import { normalize } from './model';
import { parseSource } from './parse';

function escapeTex(s: string): string {
  return s
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/([#$%&_{}])/g, '\\$1')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}');
}

function levelTikz(level: string): string {
  switch (level) {
    case '1':
    case 'u':
      return 'H';
    case '0':
    case 'd':
      return 'L';
    case 'z':
      return 'Z';
    default:
      return 'X'; // x / unknown
  }
}

/** Coalesce a signal's bricks into a tikz-timing character sequence. */
function bricksToTikz(bricks: Brick[]): string {
  let out = '';
  let i = 0;
  while (i < bricks.length) {
    const k = bricks[i]!.kind;

    if (k.type === 'clock') {
      let n = 1;
      while (i + n < bricks.length && bricks[i + n]!.kind.type === 'clock') n++;
      out += (k.polarity === 'pos' ? '0.5H0.5L' : '0.5L0.5H').repeat(n);
      i += n;
    } else if (k.type === 'level') {
      const ch = levelTikz(k.level);
      let n = 1;
      while (i + n < bricks.length) {
        const kn = bricks[i + n]!.kind;
        if (kn.type === 'level' && levelTikz(kn.level) === ch) n++;
        else break;
      }
      out += `${n > 1 ? n : ''}${ch}`;
      i += n;
    } else if (k.type === 'data') {
      let n = 1;
      while (i + n < bricks.length && bricks[i + n]!.cont && bricks[i + n]!.kind.type === 'data') n++;
      out += `${n > 1 ? n : ''}D{${escapeTex(k.label ?? '')}}`;
      i += n;
    } else {
      out += 'U'; // empty / spacer cell
      i++;
    }
  }
  return out;
}

/** Render a normalized model as a standalone tikz-timing snippet. */
export function toTikz(model: NormModel): string {
  const lines: string[] = [];
  lines.push('% Generated by WavePicGen. Requires \\usepackage{tikz-timing}.');
  if (model.head?.text) lines.push(`% ${model.head.text}`);
  lines.push('\\begin{tikztimingtable}');
  for (const r of model.rows) {
    if (r.isSpacer) {
      lines.push('  \\\\');
      continue;
    }
    lines.push(`  ${escapeTex(r.name)} & ${bricksToTikz(r.bricks)} \\\\`);
  }
  lines.push('\\end{tikztimingtable}');
  return lines.join('\n');
}

/** Parse source and produce tikz-timing code (or a parse error message). */
export function renderTikz(source: string): { tikz?: string; error?: string } {
  const { doc, error } = parseSource(source);
  if (error || !doc) return { error: error?.message ?? 'parse error' };
  return { tikz: toTikz(normalize(doc)) };
}
